const router = require("express").Router();

const passport = require("passport");
const db = require("../../../db/db.js");
const otp = require("otplib");

router.post(
  "/user/disable_2FA",
  passport.authenticate("jwt", { failWithError: true, session: false }),
  async (req, res, next) => {
    // Get user
    try {
      var user = await db.user.findOne({ where: { userid: req.user._id } });
    } catch (error) {
      return res.status(500).json({
        error: true,
        message: "Failed to get user.",
      });
    }
    if (!user.MFA_active) {
      return res.status(403).json({
        error: true,
        message: "2FA is not enabled.",
      });
    }

    if (otp.authenticator.check(req.body.totp_code, user.MFA_secret)) {
      // If the totp code provided by the user matches the one generated by the secret in the db, set 2FA as inactive
      try {
        await db.user.update(
          { MFA_active: false },
          { where: { userid: req.user._id } }
        );
      } catch (error) {
        return res
          .status(500)
          .json({ error: true, message: "Failed to disable 2FA." });
      }
      return res.status(200).json({
        error: false,
        message: "2FA disabled successfully.",
      });
    }
    return res.status(403).json({
      error: true,
      message: "Incorrect TOTP code.",
    });
  }
);

module.exports = router;
